### ISSUE TITLE
Enable LuaJIT PPC interpreter on PPC64

### ISSUE THREAD

**Issue by edelsohn** [mwkmwkmwk/LuaJIT#1]
Fix the existing ppc interpreter to work on powerpc64-linux (with no JIT and no FFI).

**Comment by mwkmwkmwk** [comment]
Done in 34c33321dcc49939aeb997a1d04e0e6b3c1ddcb6, but more tests pending.

**Comment by mwkmwkmwk** [comment]
Done and tested.
